### ISSUE TITLE
Social Media Links in Contact Page

### ISSUE THREAD

**Issue by McRawly** [McRawly/ParkProject#19]
Aggregate links for social media icons.
try coast to coast and/or infowars, wikileaks, etc. 
mufon
unsolved mysteries
ancient aliens

**Comment by valeryg95** [comment]
<div class="social-links">
                            <h2>Follow us on:</h2>
                            <a target="_blank" rel="noopener noreferrer" href="https://www.facebook.com/wikileaks"><i class="fa fa-facebook"></i></a>
                            <a target="_blank" rel="noopener noreferrer" href="https://www.instagram.com/mutualufonetwork/"><i class="fa fa-instagram"></i></a>
                            <a target="_blank" rel="noopener noreferrer" href="https://www.history.com/shows/ancient-aliens"><i class="fa fa-linkedin"></i></a>
                            <a target="_blank" rel="noopener noreferrer" href="https://www.periscope.tv/Infowars_Live/1ypKdYOmdvQGW"><i class="fa fa-pinterest"></i></a>
                            <a target="_blank" rel="noopener noreferrer" href="https://www.twitter.com/unsolved"><i class="fa fa-twitter"></i></a>
                            <a target="_blank" rel="noopener noreferrer" href="https://www.youtube.com/channel/UCVmlEoDSeImXV5aPz8EvP0A"><i class="fa fa-youtube-play"></i></a>
                        </div>

**Comment by McRawly** [comment]
great, next time you push a commit, be sure to use "fixes issue #19" or similar in your description and github will automatically add a comment here of that commit. I'm closing the issue. thanks!
